(ql:quickload "cl-glu")
(ql:quickload "cl-glfw3")
(ql:quickload "alexandria")

(defparameter *path-prefix* "projects/game/")
(defparameter *my-error-log* nil)
(defparameter *my-main-window* nil)
(defparameter *update-queue* nil)

(load (concatenate 'string *path-prefix* "agents.lisp"))
(load (concatenate 'string *path-prefix* "input.lisp"))
(load (concatenate 'string *path-prefix* "graphics.lisp"))
(load (concatenate 'string *path-prefix* "maps.lisp"))

(declaim (optimize (debug 3)))
;(declaim (optimize (speed 3) (space 2) (debug 0) (safety 0)))

;(compile-file (concatenate 'string *path-prefix* "agents.lisp"))
;(compile-file (concatenate 'string *path-prefix* "input.lisp"))
;(compile-file (concatenate 'string *path-prefix* "graphics.lisp"))
;(compile-file (concatenate 'string *path-prefix* "maps.lisp"))

(defun initialize-game ()
  (setf *my-error-log* (open "error.log" :direction :output :if-exists :supersede))
  (initialize-agent :player)
  (initialize-agent :enemy)
  (initialize-agent :enemy)
  (initialize-agent :enemy)
  (initialize-main-window))

(defun exec-key (key)
  (case key
	 ((:9 :kp-9) (move (get-player) 9))
	 ((:8 :kp-8) (move (get-player) 8))
	 ((:7 :kp-7) (move (get-player) 7))
	 ((:6 :kp-6) (move (get-player) 6))
	 ((:4 :kp-4) (move (get-player) 4))
	 ((:3 :kp-3) (move (get-player) 3))
	 ((:2 :kp-2) (move (get-player) 2))
	 ((:1 :kp-1) (move (get-player) 1))
	 (t (princ "not found~%"))))

	(defun update ()
  (dolist (key *update-queue*)
	 (exec-key key))
  (setf *update-queue* nil)
  (update-agents))

(defun close-down ()
  (close *my-error-log*)
  (close-glfw-and-window))

(defun run-game (main-window)
  (unless (%glfw:window-should-close-p main-window)
	 (input-processing)
	 (update)
	 (render (agent-location (get-player)))
	 (run-game main-window)))

(defun start ()
  (load (concatenate 'string *path-prefix* "game.lisp"))
  (let ((main-window (initialize-game)))
	 (setf *my-main-window* main-window)
	 (run-game main-window))
  (close-down))
